import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/core/css/globals.css";
import { Navbar } from "@/presentation/navbar/navbar";
import { NavProvider } from "@/core/contexts/nav-context";
const geistSans = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavProvider>
          <div>
            <Navbar />
          </div>
          {children}
        </NavProvider>
      </body>
    </html>
  );
}
